### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by JoCat** [zeroKilo/GROBackendWV#5]
Hi, I would like to thank you for the code and the wiki. I am currently developing a server for Company of Heroes and your information helps me a lot, thanks again 😉👍

**Comment by matthias-hoste** [comment]
Does CoH use the same network protocol? That's really interesting, if you want we could have a chat on discord: LifeCoder#1816

**Comment by JoCat** [comment]
> Does CoH use the same network protocol?

It looks like it. 

> That's really interesting, if you want we could have a chat on discord: LifeCoder#1816

Since my primary language is not English and I don't know it well, I can communicate in text format)
I'm JCat 🎄#6084, already threw a request to be added as a friend
