### ISSUE TITLE
Support needed for other prudp game

### ISSUE THREAD

**Issue by K4CZP3R** [zeroKilo/GROBackendWV#6]
Hi, can I get in thouch with someone from the maintainers?

We are trying to generate valid checksum (for another ubisoft game which uses prudp protocol too), but the access key is needed for that. There is no info about it inside the game, it looks like it's handled by the unreal scripts using JIT.

**Comment by zeroKilo** [comment]
im on discord (wv#9312), just contact me there. btw im all the maintainers :D

PS: have you checked the wiki yet?

**Comment by K4CZP3R** [comment]
I did, but could not find anything about obtaining an access key.

PS: I've sent you an invitation (K4CZP3R#8167)
